name: 'Curriculum Notify'
description: 'Notification action for curriculum repository'
author: 'mswnlz'
inputs:
  message:
    description: 'The message to print'
    required: false
    default: 'Hello from Curriculum Action!'
runs:
  using: 'node20'
  main: 'index.js'
